services:
  conduit:
    hostname: conduit
    image: matrixconduit/matrix-conduit:next
    restart: unless-stopped
    volumes:
      - ./conduit/db:/var/lib/matrix-conduit/
    environment:
      - CONDUIT_SERVER_NAME=example.com # Change this to your domain
      - CONDUIT_DATABASE_PATH=/var/lib/matrix-conduit/
      - CONDUIT_DATABASE_BACKEND=rocksdb
      - CONDUIT_PORT=8448
      - CONDUIT_MAX_REQUEST_SIZE=25000000
      - CONDUIT_ALLOW_REGISTRATION=true # Change this to false unless you want anybody to be able to create accounts on your homeserver
      - CONDUIT_ALLOW_FEDERATION=true
      - CONDUIT_ALLOW_CHECK_FOR_UPDATES=true
      - CONDUIT_ENABLE_LIGHTNING_BOLT=false
      - CONDUIT_TRUSTED_SERVERS=["matrix.org"]
      - CONDUIT_MAX_CONCURRENT_REQUESTS=100
      - CONDUIT_ADDRESS=0.0.0.0
      - CONDUIT_CONFIG=''
    networks:
      - external
      - internal

  cinny:
    hostname: cinny
    image: ghcr.io/cinnyapp/cinny:latest
    restart: unless-stopped
    volumes:
      - ./cinny/config.json:/app/config.json
    networks:
      - internal

  caddy:
    hostname: caddy
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - external
      - internal
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config

networks:
  external:
  internal:
    internal: true